### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by X-Tender** [Aternus/geonames-client#4]
Hi,

I get this exception thrown since today when I try to create a new client.
`cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)`

Honestly I don't know what to do with it, my SSL certificates are ok.
What's strange is that on a another project which is on the same server (just another subdomain, also with a Let's encrypt certificate) the Problem didn't appear.

Did someone have a clue what could cause it?

**Comment by Aternus** [comment]
Hey @X-Tender , looks like the `cacert.pem` CA certificate store file provided for compatibility reasons was outdated.
Newer servers tend to use the OS's CA certificate store file which might explain why one of your servers is still working properly.

Please let me know if version 2.2.1 works as expected.

**Comment by X-Tender** [comment]
We've running on th V1 currently, but I replaced the pem file with new new one and it worked.
