### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by drSun** [Aternus/geonames-client#5]
Hi guys,
At first, thank you for your excellent work. Unfortunately I get the error below, when using this extension:

```
GuzzleHttp\Exception\RequestException

cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://secure.geonames.org/countryInfoJSON?lang=ru&username=books_bvks
```

I've updated the extension to the latest version and now I have an updated cacert.pem, but this didn't help me, and the error is still there.

Any ideas?

**Comment by Aternus** [comment]
Hey @drSun , are you still experiencing the issue? Depending on your PHP configuration you might need to restart your server.
