### ISSUE TITLE
Wrong Base URL for Premium usage

### ISSUE THREAD

**Issue by antonhedling** [Aternus/geonames-client#6]
When using the Premium Data plan the Base URL should be `https://secure.geonames.net` instead of `https://secure.geonames.org`.

This information came from the email when purchasing a Premium plan

`We have enabled your account and you can access the premium server with the domain ws.geonames.net and the ssl domain is https://secure.geonames.net (.net instead of .org for the free server)`

This seems to be the case for me as well since I seem to have hit the credits cap on the .org domain while .net works.

There's currently no way to properly override this. I suggest that we either have an additional parameter in the constructor, or move the base url to a config variable.

**Comment by kreznik-augury** [comment]
Hey @antonhedling I'd be happy to explore a way to integrate the change into the code. Please reach out to me kiril at atern dot us

**Comment by Aternus** [comment]
I've sent Marc (the owner of GeoNames) an email about compatibility with the premium plan. Hopefully, we'll sort things out over the next couple of weeks.

**Comment by Aternus** [comment]
Resolved in #12
